function setting = ExeLoadSimpleBlackWhiteBoard()
    setting = struct( ...
        'InputFolder', '..\..\SourceImages\000_Sample',...
        'InputConfigFilePath', '..\..\SourceImages\000_Sample\config.txt',...
        'InputRawDPDFilePath', '..\..\SourceImages\000_Sample\pdaf_input__undefined_time__0.raw',...
        'InputRawWidth', 4032,...
        'InputRawHeight', 756,...
        'InputSensorType', 1, ...
        'InputRawCalibrationBinary', '..\..\SourceImages\003_LowlightFlatWall\2PD_DUMP_DATA_FULLSWEEP\pdaf_cali_dump.bin',...
        'OutputFolder', '..\..\ProcessedResults\000_Sample',...
        'OutputResultInfoPath', '..\..\ProcessedResults\000_Sample\pdaf_input__undefined_time__0_result.txt',...
        'OutputSadInfoPath', '..\..\ProcessedResults\000_Sample\pdaf_input__undefined_time__0_line_sad.txt',...
        'OutputCalibInfoPath', '..\..\ProcessedResults\000_Sample\pdaf_input__undefined_time__0_calib.txt');
end
