function result = ParseResultLog(dst_log_path)
    fid = fopen(dst_log_path);
    txt = textscan(fid,'%s %f','delimiter',' ');
    fclose(fid);
    
    result = struct('defocus_um', TxtFindValueByField(txt, 'defocus_um'),...
                    'phase_diff', TxtFindValueByField(txt, 'phase_diff'),...
                    'conf_level', TxtFindValueByField(txt, 'conf_level'),...
                    'start_x', TxtFindValueByField(txt, 'start_x'),...
                    'end_x', TxtFindValueByField(txt, 'end_x'),...
                    'start_y', TxtFindValueByField(txt, 'start_y'),...
                    'end_y', TxtFindValueByField(txt, 'end_y') );
end

